# -*- coding: utf-8 -*-

blogs = [
 "mundobpmn","aprendatecnologiablog",
 "desvendandoatecnologia","aprendavocemesmoti",
 "novidadesemtiblog","vidradosemtecnologia",
 "falandodetecnologiadainformacao","universotiblog",
 "tudosobretecnologiati","umpoucosobretudoti","colecaodeartigossobreti",
 "tudoqueexistesobreti","detudoumpoucoinformatica",
 "tiacessivel","mundodigitalatual","dicasetruquestecnologia",
 "tecnologiadoaaoz","cantinhodainformaticaetecnologia",
 "foradacasinhatecnologia","tempodeaprenderti",
 "aprendendosozinhoti","abcdatecnologiadainformacao",
 "blogdescomplicandoti","tiparatodosesemsegredos","mundodigitalaoseualcance",
 "nerdzoneti","mundogeekTI","tiparapessoascomuns",
 "maravilhasdatecnologia","",
 "amantesdatecnologiati","zerobitsinformatica","tiemdoseshomeopaticas",
 "gotasdeti","tecnomundonovo","ozentismo","atualidadesti",
 "tecnoferas","fiquepordentroti","tidecaboarabo","liderancati",
 "100porcentoti","24por7pensandoti","viciadosemtecnologia2016",
 "ctrlaltdelinformatica","ctrlZtecnologia","sempanicoti",
 "somenteosnerdssaofelizes","sosnaoteminternet","anjosdati",
 "bitsebytesinformatica","vidadigitaltecnologia","virtualidadetecnologia",
 "semmedodocomputador","cantinhovirtualetecnologia","docpdparaacloud",
 "doladodeforadamatrix","truquesedicasetctecnologia",
 "supergeeksti","salvesequemsouber","admiravelmundonovodati",
 "submundodainformacao","tinapalmadasuamao","tiparaleigos2016",
 "1001coisasrelacionadasati" ,"maravilhasdatecnologiamoderna",
 "tisemmisterios","ofuturojachegou","cienciaetecnologiafacil",
 "naoemagicaetecnologia" , 'pensando24horasemTI','fomedetecnologia',
 'admiravelmundonovodati','365diasfalandoemti','aquitemtecnologia',
  'novidadestecnologicasparavoce','f5tecnologiaatualizada',
 'oscaminhosdatecnologia','vivamelhoraprendatecnologia','ocerebrodigital',
 'ofiodameadaTI','temposmodernosti','dodosaoios','infowatchers',
 'desafiosdatecnologia','TInformandosobreTI','acasadosgeeks','antenadosnati',
 'conhecimentoepoderti','foradacaixati',
 'maravilhasmodernasti','semmedodatecnologiati','brainwareti','gigaminds',
 'dotransistoracloud','novoshorizontesdati','tecnonerds2016',
 '2016umaodisseianati','muitoalemdamatrix','cyberlifeti']


nomes = [ "Mundo BPMN","Aprenda Tecnologia",
          "Desevendando a Tecnologia","Aprenda Você Mesmo TI",
          "Novidades em TI","Vidrados em Tecnologia",
          "Falando de Tecnologia da Informação","Universo TI",
          "Tudo Sobre Tecnologia - TI","Um Pouco Sobre Tudo em TI",
          "Coleção de Artigos Sobre TI","Tudo que Existe Sobre TI",
          "De Tudo Um Pouco Informática","TI Acessível",
          "Mundo Digital Atual","Dicas e Truques - Tecnologia",
          "Tecnologia do A ao Z","Cantinho da Informatica e Tecnologia",
          "Fora da Casinha Tecnologia","Tempo de Aprender TI",
          "Aprendendo Sozinho TI","ABC da Tecnologia da Informação",
          "Blog Descomplicando TI","TI para Todos e Sem Segredos",
          "Mundo Digital ao Seu Alcance","Nerd Zone TI",
          "Mundo Geek TI","TI para Pessoas Comuns",
          "Maravilhas da Tecnologia","O Diario de um Nerd 2016",
          "Amantes da Tecnologia - TI","Zero Bits Informática",
          "TI em Doses Homeopáticas","Gotas de TI","Tecno Mundo Novo",
          "O Zen TIsmo","Atualidades TI","Tecno Feras",
          "Fique Por Dentro da TI","TI de Cabo a Rabo","Liderança em TI",
          "100% Tecnologia da Informação","24/7 Pensando em TI",
          "Viciados em Tecnologia 2016","CTRL+ALT+DEL Informática",
          "Ctrl+Z Tecnologia", "Sem Pânico! na TI",
          "Somente os Nerds São Felizes", "S.O.S. Não tem Internet",
          "Anjos da TI", "Bits e Bytes Informática",
          "Vida Digital Tecnologia","Virtualidade - Tecnologia",
          "Sem Medo do Computador!","Cantinho Virtual - Refúgio da Tecnologia",
          "Do CPD para a Cloud","Do lado de fora da Matrix",
          "Truques, Dicas e etc. em Tecnologia","Super Geekts (TI)",
          "Salve-se quem Souber (TI)","Admirável Mundo Novo da TI",
          "(Sub)mundo da Informação","TI na Palma da Sua Mão",
          "TI para leigos - 2016","1001 Coisas Relacionadas à TI",
          "Maravilhas da Tecnologia Moderna","TI sem Mistérios",
          "O Futuro já Chegou","Ciência e Tecnologia Fácil",
          "Não é Mágica, é Tecnologia" ,"Pensando 24 horas em TI",
          "Fome de Tecnologia","Admirável Mundo Novo da TI",
          "365 dias Falando em TI","Aqui tem Tecnologia",
          'Novidades Tecnológicas Para Você','F5 - Tecnologia Atualizada',
          'Os Caminhos da Tecnologia','Viva melhor: aprenda tecnologia',
          'O Cérebro Digital','O Fio da Meada - TI','Tempos Modernos - TI',
          'Do D.O.S. ao iOS','Info Watchers', 'Desafios da Tecnologia',
          'TInformando sobre TI','A Casa dos Geeks','Antenados na TI',
           'Conhecimento é Poder - TI','Fora da Caixa TI',
           'Maravilhas Modernas da TI','Sem Medo da Tecnologia - TI',
           'BrainWare - TI','GigaMinds','Do Transistor à Cloud',
           'Novos Horizontes da TI','Tecno Nerds 2016',
           '2016 uma odisseia na TI','Muito Além da Matrix','Cyberlife TI']


saibamais = [ "Descubra mais sobre o assunto, ",
              "Saiba mais seguindo o link para o site da matéria ",
              "Você pode ver o conteúdo completo ",
              "Se quiser saber mais, vá ao site original ",
              "Veja a matéria completa ",
              "Não deixe de ler todo o conteúdo ",
              "Para ler tudo, siga para o site do conteúdo ",
              "Para saber mais, vá ao conteudo original ",
              "Vá direto à fonte deste post, " ] #clicando aqui


visite = ["Visite também nosso site parceiro: ",
          "Não deixe de visitar nosso blog parceiro: ",
          "Também pode lhe interessar este site: ",
          "Outro blog que pode ser do seu interesse: ",
          "Se você gosta de tecnologia, pode ser que goste também do blog ",
          "Para conhecer mais sobre TI, recomendamos: ",
          "Buscando mais informação? Dê uma olhada em ",
          "Para quem curte TI, recomendamos também: "]

antes = [ "Trazendo novidades e informações para nossos leitores!",
          "Não deixe de se informar todo dia, com nosso blog.",
          "Aqui você tem novidades todos os dias.",
          "Novidades e informações para você, aqui em nosso blog...",
          "Mais um dia, mais um post. Sempre buscando deixar seu dia mais cheio de informações!"]

depois = [ "Obrigado pela sua visita! Esperamos lhe ver aqui novamente em breve.",
           "Espero que tem achado o post útil. Não se esqueça de compartilhar!",
           "Vejo vocês em breve, em mais um post sobre tecnologia.",
           "Até a próxima!",
           "Agradecemos a visita e esperamos que volte sempre por aqui!",
           "Esperamos que tenha gostado e desejamos lhe encontrar no futuro por aqui..."]

print "Total de blogs: ",len(blogs),len(nomes)
